### ISSUE TITLE
ESP8266 support

### ISSUE THREAD

**Issue by matiasinsaurralde** [Fluepke/esptool#2]
Hi, I'm currently studying the ESP chip [serial protocol](https://github.com/espressif/esptool/wiki/Serial-Protocol) and I've found `esptool` to be a great reference.
Do you have any idea of implementation changes required to support ESP8266 with your tool.

Thanks

**Comment by Fluepke** [comment]
Hi, I'm not planning on adding `ESP8266` support to my tool.

My designs are not based on the `ESP8266`. I use this tool to embed it into standalone firmware update utilities, so my customers can update their hardware easily and don't need to install python / a shitload of dependencies. It is not intended to serve as a replacement for the `esptool`.

You are welcome to contribute to this project: Please feel free to add your required features, which should be possible (first upload a software bootloader using restricted ESP8266 ROM instruction set to memory and then continue as usual).

I work as a freelancer, please contact me at sales@fluep.ke if needed.
